version: '2'

services:
  reading-is-good-app:
    image: 'reading-is-good-app:latest'
    build:
      context: .
    container_name: reading-is-good-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_PLATFORM=org.hibernate.dialect.PostgreSQLDialect

  postgres:
    image: 'postgres:14.3-alpine'
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres