spring:
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
    hibernate.ddl-auto: validate
    database-platform: ${DB_PLATFORM:org.hibernate.dialect.H2Dialect}
  application:
    name: reading-is-good
  datasource:
    url: ${DB_URL:jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:sa}
  liquibase:
    change-log: classpath:changelog/db-changelog.yml
  web.resources.add-mappings: false
  mvc.throw-exception-if-no-handler-found: true
server.servlet.encoding.force: true
logging.level.org.zalando.logbook: TRACE
security:
  users:
    - username: admin
      password: admin
      roles: USER, ADMIN
    - username: user
      password: password
      roles: USER